<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>coolOrange.MsOffice</RootNamespace>
    <AssemblyName>coolOrange.MsOffice</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyTitle>MSOfficeApplication</AssemblyTitle>
    <Description>MSOfficeApplication for powerJobs Processor</Description>
    <Product>MSOfficeApplication</Product>
    <Copyright>Copyright ©  2020</Copyright>
    <AssemblyVersion>1.0.%2a</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <StartAction>Program</StartAction>
    <StartProgram>$(windir)\System32\WindowsPowerShell\v1.0\powershell.exe</StartProgram>
    <StartArguments>-noexit -command "Import-Module powerJobs"</StartArguments>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>false</Optimize>
    <OutputPath>..\powerJobs\Modules\MsOffice\</OutputPath>
    <StartAction>Program</StartAction>
    <StartProgram>$(windir)\System32\WindowsPowerShell\v1.0\powershell.exe</StartProgram>
    <StartArguments>-noexit -command "Import-Module powerJobs"</StartArguments>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.Office.Interop.Excel" Version="16.0.18925.20022" />
    <PackageReference Include="Microsoft.Office.Interop.PowerPoint" Version="15.0.4420.1018" />
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
  </ItemGroup>
  <ItemGroup>
    <COMReference Include="VBIDE">
      <Guid>{0002E157-0000-0000-C000-000000000046}</Guid>
      <VersionMajor>5</VersionMajor>
      <VersionMinor>3</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>primary</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="office">
      <HintPath>References\OFFICE.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="powerJobs.Common">
      <HintPath>..\..\..\..\..\Program Files\coolOrange\powerJobs Processor\powerJobs.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <None Update="References\OFFICE.dll">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>